{{同人专辑头部}}

== 专辑信息 ==
{{同人专辑信息|
| 封面 = jpg
| 封面角色 = 雾雨魔理沙（旧作角色），
| 名称 = Phantasmagoria of F.M
| 译名 = 
| 制作方 = +tek
| 首发日期 = 2020-12-23
| 编号 = 
| 类型 = 全长，
| 风格类型 = 游戏音乐，
| 售价 = 免费
| 售价补充 = （Bandcamp下载，价格自定，可能因特殊情况而改价）
| 官网页面 = https://plustek.bandcamp.com/album/phantasmagoria-of-f-m
| 
}}
{{通贩列表|
| 官方 = {{通贩网址|
| 类型 = BANDCAMP
| 编号 = https://plustek.bandcamp.com/album/phantasmagoria-of-f-m
| 标题 = 
}}


| 代理 = 

| 代购 = 

}}

== Staff ==
{{专辑人员列表|
|碟号=1
|替换=
+tek
Rumya=https://soundcloud.com/ruumya SoundCloud: ruumya

}}
; Illustration : Lovely （[https://twitter.com/atelierLovely Twitter: @atelierLovely]）

== 试听 ==
{{专辑音频|
| 类型 = SoundCloudPL
| 编号 = 1183155838
| 标题 = 
}}
{{专辑音频|
| 类型 = Youtube
| 编号 = xcGJFyXmZGg
| 标题 = 
}}

== 曲目列表 ==
{{专辑曲目列表|
| 嵌套 =
{{同人曲目信息|
|名称 = Maiden's Capriccio ~ Dream Battle
|时长 = 5:28
|编曲 = +tek
|原曲 = {{永夜抄音乐名|3|9}}，
}}
{{同人曲目信息|
|名称 = Joutounin of Ceramics
|时长 = 4:07
|编曲 = +tek
|原曲 = {{鬼形兽音乐名|3|11}}，
}}
{{同人曲目信息|
|名称 = Nostalgic Blood of the East ~ Old World
|时长 = 2:48
|编曲 = +tek
|原曲 = {{永夜抄音乐名|3|6}}，
}}
{{同人曲目信息|
|名称 = The Doll Maker of Bucuresti
|时长 = 4:32
|编曲 = +tek
|原曲 = {{妖妖梦音乐名|3|6}}，
}}
{{同人曲目信息|
|名称 = Sailor of Time
|时长 = 3:58
|编曲 = +tek
|原曲 = {{梦时空音乐名|3|11}}，
}}
{{同人曲目信息|
|名称 = Pierrot of the Star-Spangled Banner
|时长 = 4:06
|编曲 = +tek
|原曲 = {{绀珠传音乐名|3|11}}，
}}
{{同人曲目信息|
|名称 = Because Princess Inada Is Scolding Me
|时长 = 2:10
|编曲 = +tek
|原曲 = {{风神录音乐名|3|3}}，
}}
{{同人曲目信息|
|名称 = Captain Murasa
|时长 = 4:05
|编曲 = +tek
|原曲 = {{星莲船音乐名|3|9}}，
}}
{{同人曲目信息|
|名称 = the Grimoire of Alice
|时长 = 3:13
|编曲 = +tek
|原曲 = {{怪绮谈音乐名|3|17}}，
}}
{{同人曲目信息|
|名称 = Mystical Maple ~ Eternal Dream
|时长 = 2:12
|编曲 = +tek
|原曲 = {{永夜抄音乐名|3|20}}，
}}
{{同人曲目信息|
|名称 = Apparitions Stalk the Night
|时长 = 2:45
|编曲 = Rumya
|原曲 = {{红魔乡音乐名|3|3}}，
}}
{{同人曲目信息|
|名称 = Satori Maiden ~ 3rd Eye
|时长 = 4:15
|编曲 = Rumya
|原曲 = {{地灵殿音乐名|3|9}}，
}}
{{同人曲目信息|
|名称 = Fall of Fall ~ Autumnal Waterfall
|时长 = 6:33
|编曲 = Rumya
|原曲 = {{风神录音乐名|3|8}}，
}}
{{同人曲目信息|
|名称 = Mystic Oriental Dream ~ Ancient Temple
|时长 = 3:20
|编曲 = Rumya
|原曲 = {{妖妖梦音乐名|3|10}}，
}}
{{同人曲目信息|
|名称 = Faith is for the Transient People
|时长 = 5:47
|编曲 = Rumya
|原曲 = {{风神录音乐名|3|11}}，
}}

}}

== 评论 ==

{{Bottom}}
