{{社团头部}}

== 社团信息 ==
{{封面图
|图片={{SUBPAGENAME}}banner.png|banner
}}
{{同人社团信息|
| 社团名 = M.H.S（Mizonokuchi Hole Studio，溝口ホール工房）
| 中文名 = 
| 主要作品类型 = 同人音乐
| 成立时间 = 
| 当前状态 = 活动
| 主催 = 溝口ゆうま
| 地区 = 日本
| 官网 = http://mizohole.psne.jp
}}

== 成员名单 ==
* [[溝口ゆうま]]

== 作品列表 ==
{{简单信息框架
|列表=
{{简单专辑信息
|名称=Yuma the Best ～ 溝口ゆうま 東方ゲスト曲集 ～
}}
{{简单专辑信息
|名称=東方飛翔頭～トウホウフライングヘッド～
}}
{{简单专辑信息
|名称=東方課金厨
}}
{{简单专辑信息
|名称=東方地雷女！ -TOHO CIRCLE CLASHEEEEEER-
}}
{{简单专辑信息
|名称=好敵性クォーラル
}}
{{简单专辑信息
|名称=トウホウミュー！
}}
{{简单专辑信息
|名称=toho POP tunes vol.1
}}
{{简单专辑信息
|名称=Harmony of Twice
}}
{{简单专辑信息
|名称=toho DANCE tune vol 0.5
}}
{{简单专辑信息
|名称=Phase Transition
}}
{{简单专辑信息
|名称=TOYBOX Anniversary!!
}}
{{简单专辑信息
|名称=Root Consciousness
}}
{{简单专辑信息
|名称=DESIRE
}}

}}

== 参展信息 ==
{{社团参展列表}}

<fixed move />
{{Bottom}}
