{{同人专辑头部}}
== 专辑信息 ==
{{同人专辑信息|
| 封面 = Locus of the Eastern Dream.EX封面.jpg
| 封面角色 = 博丽灵梦（旧作角色）
| 名称 = Locus of the Eastern Dream.EX
| 译名 = 
| 制作方 = Kissing the Mirror
| 首发日期=2011-05-08
| 展会 = {{例大祭|3|8}}
| 编号 = AOD-016
| 风格类型 = 金属
| 类型 = 全长
| 会场售价 = 1,000円
| 通贩售价 = 円1,155
| 官网页面 = http://www.aod666.com/reitaisai8/#aaaa
}}

== Staff ==
; Kissing the Mirror : Wooming / Arrangement (M-1,2,3,4,5,6,7,8)
; Guest Artists : spetsnaz / Vocal (M-1,2,3,4,5,6,7,8)<br />spetsnaz / Lyrics (M-1,2,3,4,5,6,7,8)
; Cover Artwork :  AKIRA （[http://lakia.zouri.jp/]）
== 曲目列表 ==
{{专辑曲目列表|
| 嵌套 =
{{同人曲目信息|
|名称 = Chaos Collapse
|时长 = 03:20
|编曲 = Wooming
|演唱 = spetsnaz
|作词 = spetsnaz
|原曲 = {{幻想乡音乐名|3|15}}
}}
{{同人曲目信息|
|名称 = Evil Queen
|时长 = 02:28
|编曲 = Wooming
|演唱 = spetsnaz
|作词 = spetsnaz
|原曲 = {{灵异传音乐名|3|1}}
}}
{{同人曲目信息|
|名称 = Ill Vision
|时长 = 03:49
|编曲 = Wooming
|演唱 = spetsnaz
|作词 = spetsnaz
|原曲 = {{灵异传音乐名|3|3}}
}}
{{同人曲目信息|
|名称 = Insanity Concert
|时长 = 04:12
|编曲 = Wooming
|演唱 = spetsnaz
|作词 = spetsnaz
|原曲 = {{幻想乡音乐名|3|9}}
}}
{{同人曲目信息|
|名称 = Level Insanity
|时长 = 07:03
|编曲 = Wooming
|演唱 = spetsnaz
|作词 = spetsnaz
|原曲 = {{灵异传音乐名|3|10}}

}}
{{同人曲目信息|
|名称 = P.M.C
|时长 = 04:59
|编曲 = Wooming
|演唱 = spetsnaz
|作词 = spetsnaz
|原曲 = {{灵异传音乐名|3|7}}
}}
{{同人曲目信息|
|名称 = Disturbance High
|时长 = 04:22
|编曲 = Wooming
|演唱 = spetsnaz
|作词 = spetsnaz
|原曲 = {{幻想乡音乐名|3|10}}
}}
{{同人曲目信息|
|名称 = Deadly Silence
|时长 = 04:04
|编曲 = Wooming
|演唱 = spetsnaz
|作词 = spetsnaz
|原曲 = {{灵异传音乐名|3|2}}
}}
}}

== 评论 ==




{{Bottom}}
