{{社团头部}}

== 社团信息 ==
{{封面图
|图片={{PAGENAME}}banner.png|banner
}}
{{同人社团信息|
| 社团名 = Studio K.N.S.
| 中文名 = 
| 主要作品类型 = 同人音乐，
| 成立时间 = 
| 当前状态 = 休止
| 主催 = Este
| 地区 = 日本
| 官网 = http://studiokns.web.fc2.com/Studio_K.N.S./HOME.html
| 官网说明 = {{失效标记}}
}}

== 成员名单 ==
* [[Este]]
* [[Necro]]
* [[Kamiyanagi]]

== 作品列表 ==
=== 同人专辑 ===
{{简单信息框架
|列表=
{{简单专辑信息
|名称=Blooming Apparitions
}}
{{简单专辑信息
|名称=The PURPLE Exchange
}}
{{简单专辑信息
|名称=3rd Sphere
}}
{{简单专辑信息
|名称=Perfect Cherry Blossom
}}
{{简单专辑信息
|名称=Flower×Flower
}}
{{简单专辑信息
|名称=Phantasm Literature
}}
{{简单专辑信息
|名称=Phantasm Literature Instrumental
}}

}}

== 参展信息 ==
{{社团参展列表}}

== 其他信息 ==

{{Bottom}}
