{{社团头部}}

== 社团信息 ==
[[文件: {{PAGENAME}}banner2.jpg|thumb|200px|right|banner]]
[[文件: {{PAGENAME}}banner.png|thumb|200px|right|banner]]
{{同人社团信息|
| 社团名 = Lyrica's Acoustic Callow Keynote (L.A.C.K)
| 中文名 =
| 主要作品类型 = 同人音乐
| 成立时间 = 
| 当前状态 = 休止
| 主催 = アキラ（Lyrica's Acoustic Callow Keynote）
| 地区 = 日本
| 官网 = http://lack.iza-yoi.net/
}}

== 成员名单 ==
* [[アキラ（Lyrica's Acoustic Callow Keynote）|アキラ]]
* [[ライ]]
* [[菱餅]]

== 作品列表 ==
=== 同人专辑 ===
{{简单信息框架
|列表=
{{简单专辑信息
|名称=Rhythm
}}

}}

== 参展信息 ==
{{社团参展列表}}
