{{同人专辑头部}}
== 专辑信息 ==
{{同人专辑信息|
| 封面 = G.O.D封面.jpg
| 封面角色 = 八坂神奈子
| 名称 = G.O.D
| 译名 = 
| 制作方 = Kissing the Mirror
| 首发日期=2010-10-11
| 展会 = {{红楼梦|3|6}}
| 编号 = 
| 风格类型 = 金属
| 类型 = 单曲
| 售价 = 
| 官网页面 = http://www.aod666.com/
}}

== Staff ==
; Kissing the Mirror : Wooming / Arrangement (M-1)<br />Wooming / Lyrics (M-1)
; Guest Artists : spetsnaz / Vocal (M-1)<br />AKIRA / Vocal (M-1)
== 曲目列表 ==
{{专辑曲目列表|
| 嵌套 =
{{同人曲目信息|
|名称 = G.O.D
|时长 = 03:47
|编曲 = Wooming
|演唱 = spetsnaz，AKIRA
|作词 = Wooming
|原曲 = {{风神录音乐名|3|13}}
}}
}}

== 评论 ==




{{Bottom}}
