{{社团头部}}

== 社团信息 ==
{{封面图
|图片={{PAGENAME}}banner.jpg|banner
}}
{{同人社团信息|
| 社团名 = D.I.C.S.
| 中文名 = 
| 主要作品类型 = 同人音乐，
| 成立时间 = 
| 当前状态 = 活动
| 主催 = 
| 地区 = 日本
| 官网 = 
}}

== 成员名单 ==
* [[J主]] - [https://twitter.com/Jnushi Twitter]
* [[hata0]] - [https://twitter.com/hata0_xy Twitter]

== 作品列表 ==
=== 同人专辑 ===
{{简单信息框架
|列表=
{{简单专辑信息
|名称=Crystallize
}}
{{简单专辑信息
|名称=Phantasm Garden
}}
{{简单专辑信息
|名称=Lilac Memories
}}
{{简单专辑信息
|名称=The Invisible Sphere
}}
{{简单专辑信息
|名称=The Externals
}}
{{简单专辑信息
|名称=BLUE SILENCE
}}


}}


== 其他信息 ==

{{Bottom}}
