{{同人专辑头部}}

== 专辑信息 ==
{{同人专辑信息|
| 封面 = jpg
| 封面角色 = 八云紫，
| 名称 = Touhou Ambient Project III.V
| 译名 = 
| 制作方 = Stas Gavrik
| 首发日期 = 2019-02-28
| 编号 = 
| 类型 = 全长，
| 风格类型 = 其他电子，
| 售价 = 免费
| 售价补充 = （Bandcamp下载，价格自定，可能因特殊情况而改价）
| 官网页面 = https://stasgavrik.bandcamp.com/album/touhou-ambient-project-iii-v
| 
}}
{{通贩列表|
| 官方 = {{通贩网址|
| 类型 = BANDCAMP
| 编号 = https://stasgavrik.bandcamp.com/album/touhou-ambient-project-iii-v
| 标题 = 
}}


| 代理 = 

| 代购 = 

}}

== Staff ==
{{专辑人员列表|
|碟号=1
|替换=
Stas Gavrik

}}

== 曲目列表 ==
{{专辑曲目列表|
| 嵌套 =
{{同人曲目信息|
|名称 = A Dream More Scarlet than Red (Ambient Ver.)
|时长 = 1:51
|编曲 = Stas Gavrik
|原曲 = {{红魔乡音乐名|3|1}}，
}}
{{同人曲目信息|
|名称 = A Maiden's Illusionary Funeral ~ Necro-Fantasy (Ambient ver.)
|时长 = 7:07
|编曲 = Stas Gavrik
|原曲 = {{妖妖梦音乐名|3|16}}，
}}
{{同人曲目信息|
|名称 = Flowering Night (Ambient ver.)
|时长 = 4:14
|编曲 = Stas Gavrik
|原曲 = {{花映塚音乐名|3|4}}，
}}
{{同人曲目信息|
|名称 = Hartmann's Youkai Girl (Ambient Ver.)
|时长 = 8:58
|编曲 = Stas Gavrik
|原曲 = {{地灵殿音乐名|3|15}}，
}}
{{同人曲目信息|
|名称 = Doll's Story - Doll of Misery (Ambient-Orchestral ver.)
|时长 = 3:32
|编曲 = Stas Gavrik
|原曲 = {{怪绮谈音乐名|3|13}}，
}}
{{同人曲目信息|
|名称 = Hiroari Shoots a Strange Bird ~ Till When (Ambient ver.)
|时长 = 3:32
|编曲 = Stas Gavrik
|原曲 = {{妖妖梦音乐名|3|11}}，
}}
{{同人曲目信息|
|名称 = Nostalgic Blood of the East ~ Old World (Ambient Ver.)
|时长 = 5:05
|编曲 = Stas Gavrik
|原曲 = {{永夜抄音乐名|3|6}}，
}}
{{同人曲目信息|
|名称 = The Capital City of Flowers in the Sky (Ambient Ver.)
|时长 = 7:52
|编曲 = Stas Gavrik
|原曲 = {{妖妖梦音乐名|3|4-1}}，
}}
{{同人曲目信息|
|名称 = The Inevitably Forbidden Game (Ambient Ver.)
|时长 = 6:04
|编曲 = Stas Gavrik
|原曲 = {{幻想乡音乐名|3|16}}，
}}
{{同人曲目信息|
|名称 = The Rabbit Has Landed (Ambient Ver.)
|时长 = 3:49
|编曲 = Stas Gavrik
|原曲 = {{绀珠传音乐名|3|3}}，
}}
{{同人曲目信息|
|名称 = Tomorrow Will Be Special, Yesterday Was Not (Ambient Ver.)
|时长 = 7:17
|编曲 = Stas Gavrik
|原曲 = {{风神录音乐名|3|14}}，
}}

}}

== 评论 ==

{{Bottom}}
