{{社团头部}}

== 社团信息 ==
[[文件: C.H.S_banner.jpg|thumb|200px|right|Banner]]
{{同人社团信息|
| 社团名 = C.H.S
| 中文名 = 
| 主要作品类型 = 同人音乐
| 成立时间 = 2005
| 当前状态 = 转入非东方
| 主催 = t+pazolite
| 地区 = 日本
| 官网 = http://c-h-s.me/ 
}}

== 成员名单 ==
* [[t+pazolite]]

== 作品列表 ==
{{简单信息框架
|列表=
{{简单专辑信息
|名称=for the Lunatix
}}
{{简单专辑信息
|名称=Unlimited Spark!
}}
{{简单专辑信息
|名称=neetmania
}}
{{简单专辑信息
|名称=Ultra Cute！？
}}
{{简单专辑信息
|名称=Unconnected.
}}
{{简单专辑信息
|名称=Honey I Scream!
}}
{{简单专辑信息
|名称=RESetup;
}}
{{简单专辑信息
|名称=Samplejunk
}}
{{简单专辑信息
|名称=Hommaging Greats
}}
{{简单专辑信息
|名称=So Many Materials
}}
{{简单专辑信息
|名称=t&T. “tpz And TOUHOU” from 2005
}}
}}

=== 其他 ===
{{简单信息框架
|列表=
{{简单专辑信息
|名称=TOHO OVERDRIVE ＃ 001
}}

}}

== 参展信息 ==
{{社团参展列表}}

== 其他信息 ==
