import requests
import json
import os

BASE_URL = "http://localhost:5217"
HLS_PLAYLIST_PUT_URL = "/api/internal/asset/track/{trackId}/playlist"
HLS_SEGMENT_PUT_URL = "/api/internal/asset/track/{trackId}/segment"

filestruct_fp = input("Enter the filestruct (Generated by hls-file-struct-generator) path: ") or "mig.json"

def mk_segment_payload():
    template = {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "index": 0,
        "name": "string",
        "hlsSegmentPath": "string",
        "hlsPlaylistId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    }

def mk_playlist_payload():
    template = {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "type": "Master",
        "bitrate": 0,
        "hlsPlaylistPath": "string",
        "trackId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    }
